import { JellyfinApi, formatRuntime, normalizeServerUrl, getDeviceId } from './api.js';
import { store } from './store.js';
import { demoItems, demoRows, demoSearch, demoItem, demoBackdrop, demoViews } from './demo.js';
import { openPlayer } from './player.js';

const root = document.querySelector('#app');
store.load();
let api = store.state.session && !store.state.demo ? new JellyfinApi(store.state.session) : null;
let views;
const items = new Map();
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const route = () => { const [path='home', q=''] = location.hash.replace(/^#\/?/, '').split('?'); return {path, params:new URLSearchParams(q)}; };
const go = (path, params={}) => { const q = new URLSearchParams(params).toString(); location.hash = `#/${path}${q ? `?${q}` : ''}`; };
const toast = message => { const n=document.createElement('div'); n.className='toast'; n.textContent=message; document.querySelector('#toast-region').append(n); setTimeout(()=>n.remove(),3000); };

function image(item, type='Primary', width=640) {
  if (store.state.demo) return demoBackdrop(item);
  const tag = type === 'Backdrop' ? item.BackdropImageTags?.[0] : item.ImageTags?.[type];
  return api && item?.Id && tag ? api.imageUrl(item.Id,{type,maxWidth:width,tag}) : '';
}
function progress(item) { return item.RunTimeTicks ? Math.min(100,(item.UserData?.PlaybackPositionTicks||0)/item.RunTimeTicks*100) : 0; }
function card(item, landscape=false) {
  items.set(item.Id,item); const src=image(item, landscape?'Backdrop':'Primary',640); const pct=progress(item);
  return `<button class="media-card" data-open="${esc(item.Id)}"><div class="poster ${landscape?'landscape':''}">${src?`<img src="${esc(src)}" alt="" loading="lazy">`:`<div class="poster-placeholder">${esc(item.Name)}</div>`}${item.UserData?.Played?'<span class="card-badge">✓ Vu</span>':''}${pct>0&&pct<95?`<div class="card-progress"><span style="width:${pct}%"></span></div>`:''}</div>${store.state.preferences.showTitles?`<div class="card-title">${esc(item.Name)}</div><div class="card-subtitle">${esc([item.ProductionYear,formatRuntime(item.RunTimeTicks)].filter(Boolean).join(' • '))}</div>`:''}</button>`;
}
function nav() {
  const active=route().path; const links=[['home','⌂','Accueil'],['search','⌕','Recherche'],['movies','▣','Films'],['shows','▤','Séries'],['favorites','♥','Favoris'],['settings','⚙','Paramètres'],['about','ⓘ','À propos']];
  return `<aside class="side-nav"><div class="brand"><img src="./assets/icon.svg" alt=""><strong class="nav-label">Wholphin Web</strong></div><nav class="nav-items">${links.map(([p,i,l])=>`<button class="nav-button ${active===p?'active':''}" data-nav="${p}"><span class="nav-icon">${i}</span><span class="nav-label">${l}</span></button>`).join('')}</nav><button class="nav-button" data-action="logout"><span class="nav-icon">⇥</span><span class="nav-label">Déconnexion</span></button></aside>`;
}
function shell(content,title='') { const s=store.state.session||{username:'Démo'}; return `<div class="app-shell"><div class="backdrop"></div>${nav()}<main class="main"><header class="topbar"><h1>${esc(title)}</h1><div class="top-actions"><button class="btn icon" data-action="menu">☰</button><div class="user-pill"><span class="avatar">${esc((s.username||'U')[0].toUpperCase())}</span>${esc(s.username||'Utilisateur')}</div></div></header>${content}</main></div>`; }
function setBackdrop(item) { const b=document.querySelector('.backdrop'); if (!b) return; const src=image(item,'Backdrop',1920)||image(item,'Primary',1280); b.style.backgroundImage=src?`url("${src}")`:''; }
function rows(data) { return data.filter(r=>r.items?.length).map(r=>`<section class="section"><div class="section-header"><h2>${esc(r.title)}</h2></div><div class="media-row">${r.items.map(i=>card(i,r.landscape)).join('')}</div></section>`).join(''); }
function loading(title='') { root.innerHTML=shell('<div class="empty"><div class="loader"></div></div>',title); }

function login(message='') {
  root.innerHTML=`<div class="auth-page"><section class="panel auth-card"><img class="auth-logo" src="./assets/icon.svg" alt=""><h1>Wholphin Web</h1><p>Connecte ton serveur Jellyfin. Le jeton reste dans le stockage local du navigateur.</p><form class="form-grid" id="login"><div class="field"><label>Serveur</label><input class="input" name="server" placeholder="https://jellyfin.exemple.fr" required></div><div class="field"><label>Utilisateur</label><input class="input" name="username" required></div><div class="field"><label>Mot de passe</label><input class="input" name="password" type="password"></div>${message?`<div class="status error">${esc(message)}</div>`:''}<div class="auth-actions"><button class="btn primary">Connexion</button><button class="btn" type="button" id="demo">Mode démo</button></div></form></section></div>`;
  document.querySelector('#demo').onclick=()=>{store.set({demo:true,session:{username:'Démo',serverName:'Catalogue fictif',userId:'demo'}});api=null;go('home');};
  document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const serverUrl=normalizeServerUrl(f.get('server'));const client=new JellyfinApi({serverUrl,deviceId:getDeviceId()});const info=await client.publicInfo();const auth=await client.authenticate(f.get('username'),f.get('password'));const session={serverUrl,serverName:info.ServerName,serverVersion:info.Version,username:auth.User.Name,userId:auth.User.Id,token:auth.AccessToken,deviceId:client.deviceId};store.set({session,demo:false});api=new JellyfinApi(session);views=null;go('home');}catch(err){login(err.message);}};
}
async function getViews(){ return views ||= store.state.demo?demoViews:(await api.views()).Items||[]; }
async function home(){ loading('Accueil'); items.clear(); let data;if(store.state.demo)data=demoRows();else{const v=await getViews(),m=v.find(x=>x.CollectionType==='movies'),s=v.find(x=>x.CollectionType==='tvshows');const [resume,next,movies,shows]=await Promise.all([api.resume(),api.nextUp(),m?api.latest(m.Id,'Movie'):[],s?api.latest(s.Id,'Series'):[]]);data=[{title:'Continuer à regarder',items:resume.Items||resume},{title:'À suivre',items:next.Items||[]},{title:'Films récents',items:movies},{title:'Séries récentes',items:shows}];}const hero=data.flatMap(r=>r.items||[])[0];root.innerHTML=shell(`<section class="hero"><div class="hero-content"><span class="eyebrow">${store.state.demo?'Démonstration':'Jellyfin'}</span><h2>${esc(hero?.Name||'Bienvenue')}</h2><p>${esc(hero?.Overview||'Retrouve tes bibliothèques dans une interface conçue pour le grand écran.')}</p>${hero?`<div class="actions"><button class="btn primary" data-play="${hero.Id}">▶ Lire</button><button class="btn" data-open="${hero.Id}">Détails</button></div>`:''}</div></section>${rows(data)}`,'Accueil');setBackdrop(hero);bindFocus();}
async function library(kind){ loading(kind==='movies'?'Films':'Séries');items.clear();let list;if(store.state.demo)list=demoItems.filter(i=>i.Type===(kind==='movies'?'Movie':'Series'));else{const view=(await getViews()).find(v=>v.CollectionType===(kind==='movies'?'movies':'tvshows'));list=(await api.items({parentId:view?.Id,includeItemTypes:kind==='movies'?'Movie':'Series'})).Items||[];}root.innerHTML=shell(`<div class="toolbar"><input class="input" id="filter" placeholder="Filtrer…"></div><div class="media-grid" id="grid">${list.map(i=>card(i)).join('')}</div>`,kind==='movies'?'Films':'Séries');document.querySelector('#filter').oninput=e=>document.querySelector('#grid').innerHTML=list.filter(i=>i.Name.toLowerCase().includes(e.target.value.toLowerCase())).map(i=>card(i)).join('');bindFocus();setBackdrop(list[0]);}
async function search(){root.innerHTML=shell(`<form class="toolbar" id="search"><input class="input" name="q" placeholder="Film, série, épisode…" autofocus><button class="btn primary">Rechercher</button></form><div class="media-grid" id="results"></div>`,'Recherche');document.querySelector('#search').onsubmit=async e=>{e.preventDefault();const q=new FormData(e.currentTarget).get('q').trim();if(!q)return;store.addRecentSearch(q);const list=store.state.demo?demoSearch(q):(await api.search(q)).Items||[];document.querySelector('#results').innerHTML=list.map(i=>card(i)).join('');bindFocus();};setBackdrop(null);}
async function favorites(){loading('Favoris');let list=store.state.demo?demoItems.filter(i=>store.state.favorites.includes(i.Id)||i.UserData?.IsFavorite):(await api.items({filters:'IsFavorite'})).Items||[];root.innerHTML=shell(`<div class="media-grid">${list.map(i=>card(i)).join('')}</div>`,'Favoris');bindFocus();setBackdrop(list[0]);}
async function detail(id){loading('Détails');const item=store.state.demo?demoItem(id):await api.item(id);if(!item)throw new Error('Contenu introuvable');items.set(item.Id,item);let episodes='';if(item.Type==='Series'&&!store.state.demo){const seasons=(await api.seasons(item.Id)).Items||[];if(seasons[0]){const eps=(await api.episodes(item.Id,seasons[0].Id)).Items||[];episodes=`<section class="section"><h2>${esc(seasons[0].Name)}</h2><div class="media-row">${eps.map(e=>card(e,true)).join('')}</div></section>`;}}root.innerHTML=shell(`<section class="detail-layout"><div class="detail-content"><span class="eyebrow">${esc(item.Type)}</span><h1>${esc(item.Name)}</h1><div class="hero-meta"><span>${item.ProductionYear||''}</span><span>${formatRuntime(item.RunTimeTicks)}</span><span>${item.CommunityRating?`★ ${item.CommunityRating.toFixed(1)}`:''}</span></div><p class="detail-overview">${esc(item.Overview||'Aucun résumé disponible.')}</p><div class="actions"><button class="btn primary" data-play="${item.Id}">▶ Lire</button><button class="btn" data-favorite="${item.Id}">${item.UserData?.IsFavorite?'♥ Retirer':'♡ Favori'}</button><button class="btn" data-watched="${item.Id}">${item.UserData?.Played?'↶ Non vu':'✓ Vu'}</button></div></div></section>${episodes}`,'');setBackdrop(item);bindFocus();}
function settings(){const p=store.state.preferences,s=store.state.session||{};root.innerHTML=shell(`<div class="settings-grid section"><section class="setting-card"><h3>Interface</h3><label class="field">Couleur<input type="color" value="${p.accent}" data-pref="accent"></label><label><input type="checkbox" data-pref="showTitles" ${p.showTitles?'checked':''}> Afficher les titres</label><br><label><input type="checkbox" data-pref="reducedMotion" ${p.reducedMotion?'checked':''}> Réduire les animations</label></section><section class="setting-card"><h3>Lecture</h3><select data-pref="seekSeconds"><option value="5">5 secondes</option><option value="10" ${p.seekSeconds===10?'selected':''}>10 secondes</option><option value="30" ${p.seekSeconds===30?'selected':''}>30 secondes</option></select></section><section class="setting-card"><h3>Serveur</h3><p>${esc(s.serverName||'Mode démo')}<br>${esc(s.serverUrl||'Aucun serveur réel')}<br>${esc(s.serverVersion||'')}</p></section></div>`,'Paramètres');setBackdrop(null);}
function about(){root.innerHTML=shell(`<section class="panel section" style="max-width:900px"><h2>Wholphin Web</h2><p>Adaptation web non officielle de l’expérience Wholphin pour Jellyfin. Connexion réelle, bibliothèques, recherche, fiches, lecteur HTML5/HLS, navigation télécommande et PWA.</p><p>Cette version ne fournit pas MPV, ExoPlayer ni le changement automatique de fréquence HDMI. Le serveur peut transcoder les formats non pris en charge.</p><p>Distribué sous GPL-2.0 avec attribution dans <code>web/ATTRIBUTION.md</code>.</p></section>`,'À propos');setBackdrop(null);}
function bindFocus(){document.querySelectorAll('[data-open]').forEach(b=>{b.onfocus=()=>setBackdrop(items.get(b.dataset.open));b.onmouseenter=b.onfocus;});}
async function play(id){const item=items.get(id)||(store.state.demo?demoItem(id):await api.item(id));await openPlayer({item,api,demo:store.state.demo,seekSeconds:store.state.preferences.seekSeconds});}

root.onclick=async e=>{const n=e.target.closest('[data-nav],[data-action],[data-open],[data-play],[data-favorite],[data-watched]');if(!n)return;if(n.dataset.nav)go(n.dataset.nav);else if(n.dataset.open)go('item',{id:n.dataset.open});else if(n.dataset.play)play(n.dataset.play);else if(n.dataset.action==='menu')document.querySelector('.side-nav')?.classList.toggle('expanded');else if(n.dataset.action==='logout'){store.clearSession();api=null;location.hash='';login();}else if(n.dataset.favorite){const i=items.get(n.dataset.favorite),next=!i.UserData?.IsFavorite;if(store.state.demo)store.toggleDemoFavorite(i.Id);else await api.markFavorite(i.Id,next);i.UserData={...(i.UserData||{}),IsFavorite:next};n.textContent=next?'♥ Retirer':'♡ Favori';toast(next?'Ajouté aux favoris':'Retiré des favoris');}else if(n.dataset.watched){const i=items.get(n.dataset.watched),next=!i.UserData?.Played;if(!store.state.demo)await api.markPlayed(i.Id,next);i.UserData={...(i.UserData||{}),Played:next};n.textContent=next?'↶ Non vu':'✓ Vu';}};
root.onchange=e=>{const n=e.target.closest('[data-pref]');if(!n)return;const key=n.dataset.pref,value=n.type==='checkbox'?n.checked:key==='seekSeconds'?Number(n.value):n.value;store.setPreferences({[key]:value});};
function move(key){const active=document.activeElement,all=[...document.querySelectorAll('button,input,select,a[href]')].filter(x=>x.offsetParent);if(!all.includes(active))return all[0]?.focus();const r=active.getBoundingClientRect(),v={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[key];let best,score=Infinity;for(const x of all){if(x===active)continue;const q=x.getBoundingClientRect(),dx=q.left+q.width/2-(r.left+r.width/2),dy=q.top+q.height/2-(r.top+r.height/2),p=dx*v[0]+dy*v[1];if(p<=0)continue;const s=p+Math.abs(dx*v[1]-dy*v[0])*2.5;if(s<score){score=s;best=x;}}best?.focus();best?.scrollIntoView({block:'nearest',inline:'nearest'});}
document.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();move(e.key);}else if(e.key==='Escape'&&route().path!=='home')history.back();};
async function render(){if(!store.state.session&&!store.state.demo)return login();try{const {path,params}=route();if(path==='home')await home();else if(path==='movies'||path==='shows')await library(path);else if(path==='search')await search();else if(path==='favorites')await favorites();else if(path==='item')await detail(params.get('id'));else if(path==='settings')settings();else if(path==='about')about();else go('home');}catch(err){root.innerHTML=shell(`<div class="empty"><div><h2>Erreur</h2><p>${esc(err.message)}</p><button class="btn" data-nav="home">Accueil</button></div></div>`,'Erreur');}}
window.onhashchange=render;if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
